### ISSUE TITLE
Error when I use "adamw" as the optimizer (UnboundLocalError: local variable 'beta1' referenced before assignment)

### ISSUE THREAD

**Issue by farshadsm** [tjddus9597/Proxy-Anchor-CVPR2020#22]
Hi,
When I use "adamw" as the optimizer, I get the following error. Does anyone have any idea how I can resolve it? The torch version is 1.8.1.

Traceback (most recent call last):
  File "train.py", line 396, in <module>
    opt.step()
  File "/home/.conda/envs/torchdmgpu38_dev/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/.conda/envs/torchdmgpu38_dev/lib/python3.8/site-packages/torch/optim/optimizer.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/home/.conda/envs/torchdmgpu38_dev/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/.conda/envs/torchdmgpu38_dev/lib/python3.8/site-packages/torch/optim/adamw.py", line 117, in step
    beta1,
UnboundLocalError: local variable 'beta1' referenced before assignment

I appreciate your time and help.
Best,
Farshad

**Comment by farshadsm** [comment]
Hi,
I found a bug in the source code of AdamW in torch=1.8.1, which I fixed it. Now, I can execute train.py with "adamw" as the optimizer without any error.
Best,
Farshad

**Comment by KainingYing** [comment]
HOW TO SOVLE IT?
